# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mickey/Documents/coding_ground/3d-adaptive-viewpoint-sampling-coverage

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mickey/Documents/coding_ground/3d-adaptive-viewpoint-sampling-coverage

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"assimp-dev\" \"libassimp4.1.0\" \"libassimp4.1.0-dev\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mickey/Documents/coding_ground/3d-adaptive-viewpoint-sampling-coverage/CMakeFiles /home/mickey/Documents/coding_ground/3d-adaptive-viewpoint-sampling-coverage/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mickey/Documents/coding_ground/3d-adaptive-viewpoint-sampling-coverage/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AVSCPP

# Build rule for target.
AVSCPP: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AVSCPP
.PHONY : AVSCPP

# fast build rule for target.
AVSCPP/fast:
	$(MAKE) -f CMakeFiles/AVSCPP.dir/build.make CMakeFiles/AVSCPP.dir/build
.PHONY : AVSCPP/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f external/glfw/CMakeFiles/uninstall.dir/build.make external/glfw/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f external/glfw/src/CMakeFiles/glfw.dir/build.make external/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named IrrXML

# Build rule for target.
IrrXML: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 IrrXML
.PHONY : IrrXML

# fast build rule for target.
IrrXML/fast:
	$(MAKE) -f external/assimp/contrib/irrXML/CMakeFiles/IrrXML.dir/build.make external/assimp/contrib/irrXML/CMakeFiles/IrrXML.dir/build
.PHONY : IrrXML/fast

#=============================================================================
# Target rules for targets named assimp

# Build rule for target.
assimp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 assimp
.PHONY : assimp

# fast build rule for target.
assimp/fast:
	$(MAKE) -f external/assimp/code/CMakeFiles/assimp.dir/build.make external/assimp/code/CMakeFiles/assimp.dir/build
.PHONY : assimp/fast

#=============================================================================
# Target rules for targets named Bullet3OpenCL_clew

# Build rule for target.
Bullet3OpenCL_clew: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Bullet3OpenCL_clew
.PHONY : Bullet3OpenCL_clew

# fast build rule for target.
Bullet3OpenCL_clew/fast:
	$(MAKE) -f external/bullet/src/Bullet3OpenCL/CMakeFiles/Bullet3OpenCL_clew.dir/build.make external/bullet/src/Bullet3OpenCL/CMakeFiles/Bullet3OpenCL_clew.dir/build
.PHONY : Bullet3OpenCL_clew/fast

#=============================================================================
# Target rules for targets named Bullet2FileLoader

# Build rule for target.
Bullet2FileLoader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Bullet2FileLoader
.PHONY : Bullet2FileLoader

# fast build rule for target.
Bullet2FileLoader/fast:
	$(MAKE) -f external/bullet/src/Bullet3Serialize/Bullet2FileLoader/CMakeFiles/Bullet2FileLoader.dir/build.make external/bullet/src/Bullet3Serialize/Bullet2FileLoader/CMakeFiles/Bullet2FileLoader.dir/build
.PHONY : Bullet2FileLoader/fast

#=============================================================================
# Target rules for targets named Bullet3Dynamics

# Build rule for target.
Bullet3Dynamics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Bullet3Dynamics
.PHONY : Bullet3Dynamics

# fast build rule for target.
Bullet3Dynamics/fast:
	$(MAKE) -f external/bullet/src/Bullet3Dynamics/CMakeFiles/Bullet3Dynamics.dir/build.make external/bullet/src/Bullet3Dynamics/CMakeFiles/Bullet3Dynamics.dir/build
.PHONY : Bullet3Dynamics/fast

#=============================================================================
# Target rules for targets named Bullet3Collision

# Build rule for target.
Bullet3Collision: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Bullet3Collision
.PHONY : Bullet3Collision

# fast build rule for target.
Bullet3Collision/fast:
	$(MAKE) -f external/bullet/src/Bullet3Collision/CMakeFiles/Bullet3Collision.dir/build.make external/bullet/src/Bullet3Collision/CMakeFiles/Bullet3Collision.dir/build
.PHONY : Bullet3Collision/fast

#=============================================================================
# Target rules for targets named Bullet3Geometry

# Build rule for target.
Bullet3Geometry: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Bullet3Geometry
.PHONY : Bullet3Geometry

# fast build rule for target.
Bullet3Geometry/fast:
	$(MAKE) -f external/bullet/src/Bullet3Geometry/CMakeFiles/Bullet3Geometry.dir/build.make external/bullet/src/Bullet3Geometry/CMakeFiles/Bullet3Geometry.dir/build
.PHONY : Bullet3Geometry/fast

#=============================================================================
# Target rules for targets named BulletInverseDynamics

# Build rule for target.
BulletInverseDynamics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BulletInverseDynamics
.PHONY : BulletInverseDynamics

# fast build rule for target.
BulletInverseDynamics/fast:
	$(MAKE) -f external/bullet/src/BulletInverseDynamics/CMakeFiles/BulletInverseDynamics.dir/build.make external/bullet/src/BulletInverseDynamics/CMakeFiles/BulletInverseDynamics.dir/build
.PHONY : BulletInverseDynamics/fast

#=============================================================================
# Target rules for targets named BulletSoftBody

# Build rule for target.
BulletSoftBody: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BulletSoftBody
.PHONY : BulletSoftBody

# fast build rule for target.
BulletSoftBody/fast:
	$(MAKE) -f external/bullet/src/BulletSoftBody/CMakeFiles/BulletSoftBody.dir/build.make external/bullet/src/BulletSoftBody/CMakeFiles/BulletSoftBody.dir/build
.PHONY : BulletSoftBody/fast

#=============================================================================
# Target rules for targets named BulletCollision

# Build rule for target.
BulletCollision: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BulletCollision
.PHONY : BulletCollision

# fast build rule for target.
BulletCollision/fast:
	$(MAKE) -f external/bullet/src/BulletCollision/CMakeFiles/BulletCollision.dir/build.make external/bullet/src/BulletCollision/CMakeFiles/BulletCollision.dir/build
.PHONY : BulletCollision/fast

#=============================================================================
# Target rules for targets named BulletDynamics

# Build rule for target.
BulletDynamics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BulletDynamics
.PHONY : BulletDynamics

# fast build rule for target.
BulletDynamics/fast:
	$(MAKE) -f external/bullet/src/BulletDynamics/CMakeFiles/BulletDynamics.dir/build.make external/bullet/src/BulletDynamics/CMakeFiles/BulletDynamics.dir/build
.PHONY : BulletDynamics/fast

#=============================================================================
# Target rules for targets named LinearMath

# Build rule for target.
LinearMath: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 LinearMath
.PHONY : LinearMath

# fast build rule for target.
LinearMath/fast:
	$(MAKE) -f external/bullet/src/LinearMath/CMakeFiles/LinearMath.dir/build.make external/bullet/src/LinearMath/CMakeFiles/LinearMath.dir/build
.PHONY : LinearMath/fast

#=============================================================================
# Target rules for targets named Bullet3Common

# Build rule for target.
Bullet3Common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Bullet3Common
.PHONY : Bullet3Common

# fast build rule for target.
Bullet3Common/fast:
	$(MAKE) -f external/bullet/src/Bullet3Common/CMakeFiles/Bullet3Common.dir/build.make external/bullet/src/Bullet3Common/CMakeFiles/Bullet3Common.dir/build
.PHONY : Bullet3Common/fast

#=============================================================================
# Target rules for targets named lkh

# Build rule for target.
lkh: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lkh
.PHONY : lkh

# fast build rule for target.
lkh/fast:
	$(MAKE) -f external/LKH/CMakeFiles/lkh.dir/build.make external/LKH/CMakeFiles/lkh.dir/build
.PHONY : lkh/fast

AVSCPP/src/avscpp.o: AVSCPP/src/avscpp.cpp.o

.PHONY : AVSCPP/src/avscpp.o

# target to build an object file
AVSCPP/src/avscpp.cpp.o:
	$(MAKE) -f CMakeFiles/AVSCPP.dir/build.make CMakeFiles/AVSCPP.dir/AVSCPP/src/avscpp.cpp.o
.PHONY : AVSCPP/src/avscpp.cpp.o

AVSCPP/src/avscpp.i: AVSCPP/src/avscpp.cpp.i

.PHONY : AVSCPP/src/avscpp.i

# target to preprocess a source file
AVSCPP/src/avscpp.cpp.i:
	$(MAKE) -f CMakeFiles/AVSCPP.dir/build.make CMakeFiles/AVSCPP.dir/AVSCPP/src/avscpp.cpp.i
.PHONY : AVSCPP/src/avscpp.cpp.i

AVSCPP/src/avscpp.s: AVSCPP/src/avscpp.cpp.s

.PHONY : AVSCPP/src/avscpp.s

# target to generate assembly for a file
AVSCPP/src/avscpp.cpp.s:
	$(MAKE) -f CMakeFiles/AVSCPP.dir/build.make CMakeFiles/AVSCPP.dir/AVSCPP/src/avscpp.cpp.s
.PHONY : AVSCPP/src/avscpp.cpp.s

AVSCPP/src/controls.o: AVSCPP/src/controls.cpp.o

.PHONY : AVSCPP/src/controls.o

# target to build an object file
AVSCPP/src/controls.cpp.o:
	$(MAKE) -f CMakeFiles/AVSCPP.dir/build.make CMakeFiles/AVSCPP.dir/AVSCPP/src/controls.cpp.o
.PHONY : AVSCPP/src/controls.cpp.o

AVSCPP/src/controls.i: AVSCPP/src/controls.cpp.i

.PHONY : AVSCPP/src/controls.i

# target to preprocess a source file
AVSCPP/src/controls.cpp.i:
	$(MAKE) -f CMakeFiles/AVSCPP.dir/build.make CMakeFiles/AVSCPP.dir/AVSCPP/src/controls.cpp.i
.PHONY : AVSCPP/src/controls.cpp.i

AVSCPP/src/controls.s: AVSCPP/src/controls.cpp.s

.PHONY : AVSCPP/src/controls.s

# target to generate assembly for a file
AVSCPP/src/controls.cpp.s:
	$(MAKE) -f CMakeFiles/AVSCPP.dir/build.make CMakeFiles/AVSCPP.dir/AVSCPP/src/controls.cpp.s
.PHONY : AVSCPP/src/controls.cpp.s

AVSCPP/src/genviewpoint.o: AVSCPP/src/genviewpoint.cpp.o

.PHONY : AVSCPP/src/genviewpoint.o

# target to build an object file
AVSCPP/src/genviewpoint.cpp.o:
	$(MAKE) -f CMakeFiles/AVSCPP.dir/build.make CMakeFiles/AVSCPP.dir/AVSCPP/src/genviewpoint.cpp.o
.PHONY : AVSCPP/src/genviewpoint.cpp.o

AVSCPP/src/genviewpoint.i: AVSCPP/src/genviewpoint.cpp.i

.PHONY : AVSCPP/src/genviewpoint.i

# target to preprocess a source file
AVSCPP/src/genviewpoint.cpp.i:
	$(MAKE) -f CMakeFiles/AVSCPP.dir/build.make CMakeFiles/AVSCPP.dir/AVSCPP/src/genviewpoint.cpp.i
.PHONY : AVSCPP/src/genviewpoint.cpp.i

AVSCPP/src/genviewpoint.s: AVSCPP/src/genviewpoint.cpp.s

.PHONY : AVSCPP/src/genviewpoint.s

# target to generate assembly for a file
AVSCPP/src/genviewpoint.cpp.s:
	$(MAKE) -f CMakeFiles/AVSCPP.dir/build.make CMakeFiles/AVSCPP.dir/AVSCPP/src/genviewpoint.cpp.s
.PHONY : AVSCPP/src/genviewpoint.cpp.s

AVSCPP/src/main.o: AVSCPP/src/main.cpp.o

.PHONY : AVSCPP/src/main.o

# target to build an object file
AVSCPP/src/main.cpp.o:
	$(MAKE) -f CMakeFiles/AVSCPP.dir/build.make CMakeFiles/AVSCPP.dir/AVSCPP/src/main.cpp.o
.PHONY : AVSCPP/src/main.cpp.o

AVSCPP/src/main.i: AVSCPP/src/main.cpp.i

.PHONY : AVSCPP/src/main.i

# target to preprocess a source file
AVSCPP/src/main.cpp.i:
	$(MAKE) -f CMakeFiles/AVSCPP.dir/build.make CMakeFiles/AVSCPP.dir/AVSCPP/src/main.cpp.i
.PHONY : AVSCPP/src/main.cpp.i

AVSCPP/src/main.s: AVSCPP/src/main.cpp.s

.PHONY : AVSCPP/src/main.s

# target to generate assembly for a file
AVSCPP/src/main.cpp.s:
	$(MAKE) -f CMakeFiles/AVSCPP.dir/build.make CMakeFiles/AVSCPP.dir/AVSCPP/src/main.cpp.s
.PHONY : AVSCPP/src/main.cpp.s

AVSCPP/src/mesh.o: AVSCPP/src/mesh.cpp.o

.PHONY : AVSCPP/src/mesh.o

# target to build an object file
AVSCPP/src/mesh.cpp.o:
	$(MAKE) -f CMakeFiles/AVSCPP.dir/build.make CMakeFiles/AVSCPP.dir/AVSCPP/src/mesh.cpp.o
.PHONY : AVSCPP/src/mesh.cpp.o

AVSCPP/src/mesh.i: AVSCPP/src/mesh.cpp.i

.PHONY : AVSCPP/src/mesh.i

# target to preprocess a source file
AVSCPP/src/mesh.cpp.i:
	$(MAKE) -f CMakeFiles/AVSCPP.dir/build.make CMakeFiles/AVSCPP.dir/AVSCPP/src/mesh.cpp.i
.PHONY : AVSCPP/src/mesh.cpp.i

AVSCPP/src/mesh.s: AVSCPP/src/mesh.cpp.s

.PHONY : AVSCPP/src/mesh.s

# target to generate assembly for a file
AVSCPP/src/mesh.cpp.s:
	$(MAKE) -f CMakeFiles/AVSCPP.dir/build.make CMakeFiles/AVSCPP.dir/AVSCPP/src/mesh.cpp.s
.PHONY : AVSCPP/src/mesh.cpp.s

AVSCPP/src/render.o: AVSCPP/src/render.cpp.o

.PHONY : AVSCPP/src/render.o

# target to build an object file
AVSCPP/src/render.cpp.o:
	$(MAKE) -f CMakeFiles/AVSCPP.dir/build.make CMakeFiles/AVSCPP.dir/AVSCPP/src/render.cpp.o
.PHONY : AVSCPP/src/render.cpp.o

AVSCPP/src/render.i: AVSCPP/src/render.cpp.i

.PHONY : AVSCPP/src/render.i

# target to preprocess a source file
AVSCPP/src/render.cpp.i:
	$(MAKE) -f CMakeFiles/AVSCPP.dir/build.make CMakeFiles/AVSCPP.dir/AVSCPP/src/render.cpp.i
.PHONY : AVSCPP/src/render.cpp.i

AVSCPP/src/render.s: AVSCPP/src/render.cpp.s

.PHONY : AVSCPP/src/render.s

# target to generate assembly for a file
AVSCPP/src/render.cpp.s:
	$(MAKE) -f CMakeFiles/AVSCPP.dir/build.make CMakeFiles/AVSCPP.dir/AVSCPP/src/render.cpp.s
.PHONY : AVSCPP/src/render.cpp.s

AVSCPP/src/shader.o: AVSCPP/src/shader.cpp.o

.PHONY : AVSCPP/src/shader.o

# target to build an object file
AVSCPP/src/shader.cpp.o:
	$(MAKE) -f CMakeFiles/AVSCPP.dir/build.make CMakeFiles/AVSCPP.dir/AVSCPP/src/shader.cpp.o
.PHONY : AVSCPP/src/shader.cpp.o

AVSCPP/src/shader.i: AVSCPP/src/shader.cpp.i

.PHONY : AVSCPP/src/shader.i

# target to preprocess a source file
AVSCPP/src/shader.cpp.i:
	$(MAKE) -f CMakeFiles/AVSCPP.dir/build.make CMakeFiles/AVSCPP.dir/AVSCPP/src/shader.cpp.i
.PHONY : AVSCPP/src/shader.cpp.i

AVSCPP/src/shader.s: AVSCPP/src/shader.cpp.s

.PHONY : AVSCPP/src/shader.s

# target to generate assembly for a file
AVSCPP/src/shader.cpp.s:
	$(MAKE) -f CMakeFiles/AVSCPP.dir/build.make CMakeFiles/AVSCPP.dir/AVSCPP/src/shader.cpp.s
.PHONY : AVSCPP/src/shader.cpp.s

AVSCPP/src/utils.o: AVSCPP/src/utils.cpp.o

.PHONY : AVSCPP/src/utils.o

# target to build an object file
AVSCPP/src/utils.cpp.o:
	$(MAKE) -f CMakeFiles/AVSCPP.dir/build.make CMakeFiles/AVSCPP.dir/AVSCPP/src/utils.cpp.o
.PHONY : AVSCPP/src/utils.cpp.o

AVSCPP/src/utils.i: AVSCPP/src/utils.cpp.i

.PHONY : AVSCPP/src/utils.i

# target to preprocess a source file
AVSCPP/src/utils.cpp.i:
	$(MAKE) -f CMakeFiles/AVSCPP.dir/build.make CMakeFiles/AVSCPP.dir/AVSCPP/src/utils.cpp.i
.PHONY : AVSCPP/src/utils.cpp.i

AVSCPP/src/utils.s: AVSCPP/src/utils.cpp.s

.PHONY : AVSCPP/src/utils.s

# target to generate assembly for a file
AVSCPP/src/utils.cpp.s:
	$(MAKE) -f CMakeFiles/AVSCPP.dir/build.make CMakeFiles/AVSCPP.dir/AVSCPP/src/utils.cpp.s
.PHONY : AVSCPP/src/utils.cpp.s

external/glad/src/glad.o: external/glad/src/glad.c.o

.PHONY : external/glad/src/glad.o

# target to build an object file
external/glad/src/glad.c.o:
	$(MAKE) -f CMakeFiles/AVSCPP.dir/build.make CMakeFiles/AVSCPP.dir/external/glad/src/glad.c.o
.PHONY : external/glad/src/glad.c.o

external/glad/src/glad.i: external/glad/src/glad.c.i

.PHONY : external/glad/src/glad.i

# target to preprocess a source file
external/glad/src/glad.c.i:
	$(MAKE) -f CMakeFiles/AVSCPP.dir/build.make CMakeFiles/AVSCPP.dir/external/glad/src/glad.c.i
.PHONY : external/glad/src/glad.c.i

external/glad/src/glad.s: external/glad/src/glad.c.s

.PHONY : external/glad/src/glad.s

# target to generate assembly for a file
external/glad/src/glad.c.s:
	$(MAKE) -f CMakeFiles/AVSCPP.dir/build.make CMakeFiles/AVSCPP.dir/external/glad/src/glad.c.s
.PHONY : external/glad/src/glad.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... AVSCPP"
	@echo "... uninstall"
	@echo "... glfw"
	@echo "... IrrXML"
	@echo "... assimp"
	@echo "... Bullet3OpenCL_clew"
	@echo "... Bullet2FileLoader"
	@echo "... Bullet3Dynamics"
	@echo "... Bullet3Collision"
	@echo "... Bullet3Geometry"
	@echo "... BulletInverseDynamics"
	@echo "... BulletSoftBody"
	@echo "... BulletCollision"
	@echo "... BulletDynamics"
	@echo "... LinearMath"
	@echo "... Bullet3Common"
	@echo "... lkh"
	@echo "... AVSCPP/src/avscpp.o"
	@echo "... AVSCPP/src/avscpp.i"
	@echo "... AVSCPP/src/avscpp.s"
	@echo "... AVSCPP/src/controls.o"
	@echo "... AVSCPP/src/controls.i"
	@echo "... AVSCPP/src/controls.s"
	@echo "... AVSCPP/src/genviewpoint.o"
	@echo "... AVSCPP/src/genviewpoint.i"
	@echo "... AVSCPP/src/genviewpoint.s"
	@echo "... AVSCPP/src/main.o"
	@echo "... AVSCPP/src/main.i"
	@echo "... AVSCPP/src/main.s"
	@echo "... AVSCPP/src/mesh.o"
	@echo "... AVSCPP/src/mesh.i"
	@echo "... AVSCPP/src/mesh.s"
	@echo "... AVSCPP/src/render.o"
	@echo "... AVSCPP/src/render.i"
	@echo "... AVSCPP/src/render.s"
	@echo "... AVSCPP/src/shader.o"
	@echo "... AVSCPP/src/shader.i"
	@echo "... AVSCPP/src/shader.s"
	@echo "... AVSCPP/src/utils.o"
	@echo "... AVSCPP/src/utils.i"
	@echo "... AVSCPP/src/utils.s"
	@echo "... external/glad/src/glad.o"
	@echo "... external/glad/src/glad.i"
	@echo "... external/glad/src/glad.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

